import type { CollectionConfig } from 'payload'
import { isStaff, isStaffField } from '../lib/collectionAccess'

// Member accounts — replaces hub_accounts + hub_sessions + password/verify
// token tables. Payload auth provides login/logout/me/forgot/reset and
// httpOnly cookie sessions; the fields below carry YOUNGO's registration and
// lifecycle model (see docs/existing-system.md and docs/migration.md).
export const Accounts: CollectionConfig = {
  slug: 'accounts',
  auth: {
    useAPIKey: false,
    tokenExpiration: 60 * 60 * 24 * 30,
    verify: false,
    maxLoginAttempts: 10,
    lockTime: 15 * 60 * 1000,
    cookies: {
      secure: process.env.NODE_ENV === 'production',
      sameSite: 'Lax',
      domain: undefined,
    },
  },
  admin: {
    useAsTitle: 'email',
    group: 'Membership',
    defaultColumns: ['email', 'name', 'memberStatus', 'role', 'membershipTrack'],
  },
  access: {
    read: ({ req }) => {
      if (!req.user) return false
      if (req.user.collection === 'users') return true
      return { id: { equals: req.user.id } }
    },
    admin: () => false, // members never enter the console
    unlock: ({ req }) => req.user?.collection === 'users',
    // Member writes go through domain endpoints (registration, profile,
    // lifecycle review) which authorise the actor and use overrideAccess.
    create: isStaff,
    update: isStaff,
    delete: isStaff,
  },
  fields: [
    { name: 'name', type: 'text', required: true },
    { name: 'firstName', type: 'text' },
    { name: 'lastName', type: 'text' },
    { name: 'phone', type: 'text' },
    { name: 'gender', type: 'text' },
    { name: 'genderOther', type: 'text' },
    { name: 'ageBand', type: 'text' },
    { name: 'dateOfBirth', type: 'date' },
    { name: 'minorityGroups', type: 'json' },
    { name: 'minorityOther', type: 'text' },
    { name: 'region', type: 'text' },
    { name: 'nationality', type: 'text' },
    { name: 'country', type: 'text', required: true },
    { name: 'motivation', type: 'textarea' },
    {
      name: 'entityType',
      type: 'select',
      required: true,
      options: [
        { label: 'Individual', value: 'individual' },
        { label: 'Organisation', value: 'organization' },
      ],
      defaultValue: 'individual',
    },
    {
      name: 'postingTrust',
      access: { update: isStaffField },
      type: 'select',
      options: [
        { label: 'Trusted — postings go live immediately', value: 'trusted' },
        { label: 'Review required', value: 'review_required' },
      ],
      admin: {
        description:
          'Organisation posting trust override; empty derives trust from a published posting.',
        condition: (data: any) => data?.entityType === 'organization',
      },
    },
    {
      name: 'postingTrustNote',
      access: { update: isStaffField },
      type: 'textarea',
      admin: {
        description: 'Staff note recorded with the posting-trust override.',
        condition: (data: any) => data?.entityType === 'organization',
      },
    },
    {
      name: 'membershipTrack',
      access: { update: isStaffField },
      type: 'select',
      required: true,
      options: [
        { label: 'YOUNGO Network', value: 'network' },
        { label: 'Constituency Work', value: 'constituency_work' },
      ],
      defaultValue: 'network',
    },
    { name: 'organizationName', type: 'text', label: 'Organisation name' },
    { name: 'organizationType', type: 'text', label: 'Organisation type' },
    { name: 'isUnfcccAdmitted', type: 'checkbox', defaultValue: false },
    { name: 'orgOperateIn', type: 'text' },
    { name: 'orgWebsite', type: 'text' },
    { name: 'orgSocial', type: 'text' },
    { name: 'orgMission', type: 'textarea' },
    { name: 'dcpName', type: 'text', label: 'Designated contact point' },
    { name: 'dcpEmail', type: 'text' },
    { name: 'dcpPhone', type: 'text' },
    { name: 'ycpName', type: 'text', label: 'Youth contact point' },
    { name: 'ycpEmail', type: 'text' },
    { name: 'ycpPhone', type: 'text' },
    { name: 'under18', type: 'checkbox', defaultValue: false },
    { name: 'guardianName', type: 'text' },
    { name: 'guardianEmail', type: 'text' },
    { name: 'guardianConsent', access: { update: isStaffField }, type: 'checkbox', defaultValue: false },
    { name: 'memberOfAccreditedNgo', type: 'checkbox', defaultValue: false },
    { name: 'coiDeclared', type: 'checkbox', defaultValue: false },
    { name: 'coiDetails', type: 'textarea' },
    { name: 'youthAffiliation', type: 'text' },
    { name: 'acceptCodeOfConduct', type: 'checkbox', defaultValue: false },
    { name: 'acceptDataProtection', type: 'checkbox', defaultValue: false },
    { name: 'acceptPrinciples', type: 'checkbox', defaultValue: false },
    { name: 'acceptCoiPolicy', type: 'checkbox', defaultValue: false },
    { name: 'policiesAccepted', access: { update: isStaffField }, type: 'checkbox', defaultValue: false },
    { name: 'membershipPolicyVersion', access: { update: isStaffField }, type: 'text' },
    { name: 'privacyConsent', access: { update: isStaffField }, type: 'checkbox', defaultValue: false },
    { name: 'privacyConsentAt', access: { update: isStaffField }, type: 'date' },
    { name: 'privacyNoticeVersion', access: { update: isStaffField }, type: 'text' },
    { name: 'privacyConsentWithdrawnAt', access: { update: isStaffField }, type: 'date' },
    {
      name: 'memberStatus',
      access: { update: isStaffField },
      type: 'select',
      defaultValue: 'pending_course',
      options: ['pending_course', 'verified', 'suspended'],
    },
    {
      name: 'hubAccessStatus',
      access: { update: isStaffField },
      type: 'select',
      defaultValue: 'pending_course',
      options: ['pending_course', 'active', 'suspended'],
    },
    {
      name: 'membershipStatus',
      access: { update: isStaffField },
      type: 'select',
      defaultValue: 'registered',
      options: [
        'registered',
        'course_passed',
        'awaiting_onboarding',
        'active',
        'renewal_due',
        'expired',
        'terminated',
        'rejected',
      ],
      index: true,
    },
    {
      name: 'constituencyWorkStatus',
      access: { update: isStaffField },
      type: 'select',
      options: [
        { label: '—', value: '' },
        { label: 'Pending onboarding', value: 'pending_onboarding' },
        { label: 'Active', value: 'active' },
      ],
    },
    { name: 'onboardingCohort', access: { update: isStaffField }, type: 'text' },
    { name: 'renewalDueAt', access: { update: isStaffField }, type: 'date' },
    { name: 'membershipEndedAt', access: { update: isStaffField }, type: 'date' },
    { name: 'membershipEndReason', access: { update: isStaffField }, type: 'text' },
    {
      name: 'role',
      access: { update: isStaffField },
      type: 'select',
      required: true,
      defaultValue: 'member',
      options: [
        { label: 'Member', value: 'member' },
        { label: 'Administrator', value: 'admin' },
        { label: 'Focal Point', value: 'focal_point' },
        { label: 'WG Contact Point', value: 'wg_contact' },
        { label: 'Organisation admin', value: 'ngo_admin' },
      ],
      admin: { position: 'sidebar' },
    },
    { name: 'teamRoles', access: { update: isStaffField }, type: 'json' },
    { name: 'wgInterests', type: 'json' },
    { name: 'appointmentEvidence', access: { update: isStaffField }, type: 'json' },
    { name: 'coursePassedAt', access: { update: isStaffField }, type: 'date' },
    { name: 'courseScore', access: { update: isStaffField }, type: 'number' },
    { name: 'verifiedAt', access: { update: isStaffField }, type: 'date' },
    // Legacy stores the reviewer email, not a FK.
    { name: 'verifiedBy', access: { update: isStaffField }, type: 'text' },
    { name: 'emailVerifiedAt', access: { update: isStaffField }, type: 'date' },
    {
      name: 'principalType',
      access: { update: isStaffField },
      type: 'select',
      defaultValue: 'human',
      options: ['human', 'service'],
    },
    { name: 'mustChangePassword', access: { update: isStaffField }, type: 'checkbox', defaultValue: false },
    // Legacy credential support: on first login the legacy scrypt hash is
    // verified, the Payload password is set, and these are cleared.
    { name: 'legacyPasswordHash', access: { update: isStaffField }, type: 'text', admin: { readOnly: true } },
    { name: 'legacyPasswordSalt', access: { update: isStaffField }, type: 'text', admin: { readOnly: true } },
    { name: 'lastLoginAt', access: { update: isStaffField }, type: 'date', admin: { readOnly: true } },
    { name: 'legacyId', access: { update: isStaffField }, type: 'text', index: true, admin: { readOnly: true } },
  ],
}
