/**
 * Demo operational content for local development. Populates one example of
 * each workflow surface — decisions in three states, a live election, an
 * open selection, a handover, and one of each operations filing — so a fresh
 * `npm run seed` + `npm run seed:demo` database is immediately usable.
 *
 * Every record is marked `[Demo]` and explains itself; nothing here is a real
 * organisational record. Actors are the accounts provisioned by
 * `demo-accounts.ts`. Re-running upserts by deterministic keys.
 */
import crypto from 'node:crypto'
import type { Payload } from 'payload'

const H = 3_600_000
const now = () => new Date()
const iso = (d: Date) => d.toISOString()
const ago = (days: number) => iso(new Date(now().getTime() - days * 24 * H))
const ahead = (days: number) => iso(new Date(now().getTime() + days * 24 * H))
const hoursAgo = (h: number) => iso(new Date(now().getTime() - h * H))
const hoursAhead = (h: number) => iso(new Date(now().getTime() + h * H))

const DEMO_TEXT =
  'Placeholder text generated by `npm run seed:demo` to exercise the workflow. ' +
  'In a live deployment this field is written by the responsible members.'

async function upsert(
  payload: Payload,
  collection: string,
  where: any,
  data: any,
) {
  const { docs } = await payload.find({
    collection: collection as any,
    where,
    limit: 1,
    overrideAccess: true,
  })
  if (docs[0])
    return payload.update({
      collection: collection as any,
      id: docs[0].id,
      data,
      overrideAccess: true,
    })
  return payload.create({
    collection: collection as any,
    data,
    overrideAccess: true,
  })
}

// HMAC shape mirrors src/endpoints/governance.ts so demo voter credentials
// are indistinguishable from issued ones.
const voterHash = (electionId: number | string, token: string) =>
  crypto
    .createHmac('sha256', process.env.PAYLOAD_SECRET!)
    .update(`${electionId}:${token}`)
    .digest('hex')

export async function provisionDemoContent(
  payload: Payload,
  accounts: Map<string, any>,
) {
  const id = (key: string) => {
    const a = accounts.get(key)
    if (!a) throw new Error(`demo account missing: ${key}`)
    return a.id
  }
  const focal = id('focal-point')
  const admin = id('console-admin')
  const member = id('member')
  const cwFinanceMember = id('cw-finance-member')
  const cwFinanceContact = id('cw-finance-contact')
  const cwAceContact = id('cw-ace-contact')

  // ── Decisions (S09): adopted / consultation / voting ──────────────

  const p1 = await upsert(
    payload,
    'decision-proposals',
    { title: { equals: '[Demo] Adopted council decision' } },
    {
      title: '[Demo] Adopted council decision',
      context: DEMO_TEXT,
      proposalText: DEMO_TEXT,
      decisionType: 'standard',
      body: 'council',
      bodyRef: null,
      status: 'adopted',
      adoptedVia: 'vote',
      proposedBy: focal,
      contactPersons: [focal],
      presentedAt: ago(8),
      consultationEndsAt: ago(3),
      revisionEndsAt: ago(2),
      decisionEndsAt: ago(1),
      votingEndsAt: ago(0),
      eligibleVoterCount: 12,
      ballotOptions: [{ option: 'for' }, { option: 'against' }],
      votesFor: 4,
      votesAgainst: 1,
      decidedAt: ago(0),
      resultSummary:
        'Adopted by vote: 4 for, 1 against. A standing red flag was addressed but not withdrawn, so the proposal went to ballot.',
      isPublic: true,
    },
  )
  await upsert(
    payload,
    'decision-flags',
    { proposal: { equals: p1.id }, kind: { equals: 'red' } },
    {
      proposal: p1.id,
      kind: 'red',
      rationaleCategory: 'inadequate_consultation',
      reason: `Demo red flag. ${DEMO_TEXT}`,
      alternative: 'Demo alternative text.',
      raisedBy: cwFinanceContact,
      status: 'addressed',
      responseNote: DEMO_TEXT,
      respondedBy: focal,
      respondedAt: ago(2),
      raisedAt: ago(3),
    },
  )
  for (const [who, choice] of [
    [focal, 'for'],
    [cwFinanceContact, 'for'],
    [admin, 'for'],
    [cwAceContact, 'against'],
    [cwFinanceMember, 'for'],
  ] as const) {
    await upsert(
      payload,
      'decision-ballots',
      { proposal: { equals: p1.id }, account: { equals: who } },
      { proposal: p1.id, account: who, choice, castAt: ago(0) },
    )
  }
  for (const [type, actor, at, detail] of [
    ['created', focal, ago(9), null],
    ['presented', focal, ago(8), null],
    [
      'flag_red_raised',
      cwFinanceContact,
      ago(3),
      { rationaleCategory: 'inadequate_consultation' },
    ],
    ['flag_responded', focal, ago(2), null],
    ['vote_opened', null, ago(1), { eligibleVoterCount: 12 }],
    ['adopted', null, ago(0), { via: 'vote', votesFor: 4, cast: 5 }],
  ] as const) {
    await upsert(
      payload,
      'decision-events',
      { proposal: { equals: p1.id }, type: { equals: type } },
      { proposal: p1.id, type, actor, detail, createdAt: at },
    )
  }

  const p2 = await upsert(
    payload,
    'decision-proposals',
    { title: { equals: '[Demo] Council decision in consultation' } },
    {
      title: '[Demo] Council decision in consultation',
      context: DEMO_TEXT,
      proposalText: DEMO_TEXT,
      decisionType: 'standard',
      body: 'council',
      bodyRef: null,
      status: 'consultation',
      proposedBy: admin,
      contactPersons: [admin],
      presentedAt: ago(1),
      consultationEndsAt: ahead(4),
      revisionEndsAt: ahead(5),
      decisionEndsAt: ahead(6),
      isPublic: true,
    },
  )
  await upsert(
    payload,
    'decision-flags',
    { proposal: { equals: p2.id }, kind: { equals: 'grey' } },
    {
      proposal: p2.id,
      kind: 'grey',
      rationaleCategory: null,
      reason: `Demo grey flag (clarification request). ${DEMO_TEXT}`,
      raisedBy: cwFinanceMember,
      status: 'open',
      raisedAt: hoursAgo(20),
    },
  )
  for (const [who, body, at] of [
    [cwFinanceContact, `Demo consultation comment. ${DEMO_TEXT}`, hoursAgo(22)],
    [member, `Demo consultation comment. ${DEMO_TEXT}`, hoursAgo(10)],
  ] as const) {
    await upsert(
      payload,
      'decision-comments',
      { proposal: { equals: p2.id }, account: { equals: who } },
      { proposal: p2.id, account: who, body, createdAt: at },
    )
  }
  for (const [type, actor, at] of [
    ['created', admin, ago(1)],
    ['presented', admin, ago(1)],
  ] as const) {
    await upsert(
      payload,
      'decision-events',
      { proposal: { equals: p2.id }, type: { equals: type } },
      { proposal: p2.id, type, actor, detail: null, createdAt: at },
    )
  }

  const p3 = await upsert(
    payload,
    'decision-proposals',
    { title: { equals: '[Demo] Working-group snap decision in voting' } },
    {
      title: '[Demo] Working-group snap decision in voting',
      context: DEMO_TEXT,
      proposalText: DEMO_TEXT,
      decisionType: 'snap',
      snapJustification: `Demo snap justification. ${DEMO_TEXT}`,
      snapDeadline: ahead(2),
      body: 'working_group',
      bodyRef: 'finance',
      status: 'voting',
      proposedBy: cwFinanceContact,
      contactPersons: [cwFinanceContact],
      presentedAt: ago(1),
      consultationEndsAt: hoursAgo(12),
      revisionEndsAt: hoursAgo(6),
      decisionEndsAt: hoursAgo(2),
      votingEndsAt: hoursAhead(22),
      eligibleVoterCount: 8,
      ballotOptions: [{ option: 'for' }, { option: 'against' }],
      isPublic: true,
    },
  )
  await upsert(
    payload,
    'decision-flags',
    { proposal: { equals: p3.id }, kind: { equals: 'red' } },
    {
      proposal: p3.id,
      kind: 'red',
      rationaleCategory: 'mission_misalignment',
      reason: `Demo red flag. ${DEMO_TEXT}`,
      alternative: 'Demo alternative text.',
      raisedBy: cwFinanceMember,
      status: 'addressed',
      responseNote: DEMO_TEXT,
      respondedBy: cwFinanceContact,
      respondedAt: hoursAgo(8),
      raisedAt: hoursAgo(16),
    },
  )
  await upsert(
    payload,
    'decision-ballots',
    { proposal: { equals: p3.id }, account: { equals: cwFinanceContact } },
    {
      proposal: p3.id,
      account: cwFinanceContact,
      choice: 'for',
      castAt: hoursAgo(1),
    },
  )
  for (const [type, actor, at, detail] of [
    ['created', cwFinanceContact, ago(1), null],
    ['presented', cwFinanceContact, ago(1), null],
    [
      'flag_red_raised',
      cwFinanceMember,
      hoursAgo(16),
      { rationaleCategory: 'mission_misalignment' },
    ],
    ['flag_responded', cwFinanceContact, hoursAgo(8), null],
    ['vote_opened', null, hoursAgo(2), { eligibleVoterCount: 8 }],
  ] as const) {
    await upsert(
      payload,
      'decision-events',
      { proposal: { equals: p3.id }, type: { equals: type } },
      { proposal: p3.id, type, actor, detail, createdAt: at },
    )
  }

  // ── Election (S10): live voting window ────────────────────────────

  const election = await upsert(
    payload,
    'elections',
    { title: { equals: '[Demo] Coordination election' } },
    {
      title: '[Demo] Coordination election',
      kind: 'focal_point',
      status: 'voting',
      description: DEMO_TEXT,
      races: [
        { slug: 'seat-one', label: 'Seat one' },
        { slug: 'seat-two', label: 'Seat two' },
      ],
      nominationsOpenAt: ago(10),
      nominationsCloseAt: ago(4),
      votingOpensAt: ago(1),
      votingCloseAt: ahead(3),
    },
  )
  const candidates: Record<string, any> = {}
  for (const [race, account] of [
    ['seat-one', cwFinanceMember],
    ['seat-one', cwAceContact],
    ['seat-two', focal],
  ] as const) {
    const c = await upsert(
      payload,
      'election-candidates',
      {
        and: [
          { election: { equals: election.id } },
          { race: { equals: race } },
          { account: { equals: account } },
        ],
      },
      {
        election: election.id,
        race,
        account,
        statement: DEMO_TEXT,
        status: 'screened_in',
        nominatedAt: ago(6),
      },
    )
    candidates[`${race}:${account}`] = c
  }
  for (const [account, race, ranks] of [
    [cwFinanceContact, 'seat-one', [cwAceContact, cwFinanceMember]],
    [cwFinanceMember, 'seat-one', [cwFinanceMember]],
    [member, 'seat-one', []],
    [focal, 'seat-one', null],
  ] as const) {
    const token = crypto.randomUUID()
    const hash = voterHash(election.id, token)
    await upsert(
      payload,
      'election-voters',
      {
        and: [
          { election: { equals: election.id } },
          { account: { equals: account } },
          { kind: { equals: 'individual' } },
        ],
      },
      {
        election: election.id,
        account,
        kind: 'individual',
        tokenHash: hash,
        issuedAt: ago(2),
        votedAt: ranks === null ? null : hoursAgo(6),
      },
    )
    if (ranks !== null) {
      await upsert(
        payload,
        'election-ballots',
        {
          and: [
            { election: { equals: election.id } },
            { race: { equals: race } },
            { voterTokenHash: { equals: hash } },
          ],
        },
        {
          election: election.id,
          race,
          voterTokenHash: hash,
          kind: 'individual',
          ranks: ranks.map(
            (accountId) =>
              (candidates[`${race}:${accountId}`] as any)?.id ?? accountId,
          ),
          castAt: hoursAgo(6),
        },
      )
    }
  }

  // ── Selection (S24): open window with committee + applications ────

  const selection = await upsert(
    payload,
    'selections',
    { title: { equals: '[Demo] Open selection' } },
    {
      title: '[Demo] Open selection',
      opportunityNote: DEMO_TEXT,
      kind: 'standard',
      status: 'open',
      method: 'numerical',
      criteria: [{ name: 'Demo criterion', weightPct: 100 }],
      deadlineAt: ahead(7),
      createdBy: admin,
    },
  )
  for (const account of [focal, cwFinanceContact, cwAceContact]) {
    await upsert(
      payload,
      'selection-committee',
      {
        and: [
          { selection: { equals: selection.id } },
          { account: { equals: account } },
        ],
      },
      { selection: selection.id, account, joinedAt: ago(3) },
    )
  }
  for (const account of [cwFinanceMember, member]) {
    await upsert(
      payload,
      'selection-applications',
      {
        and: [
          { selection: { equals: selection.id } },
          { account: { equals: account } },
        ],
      },
      {
        selection: selection.id,
        account,
        answers: [{ question: 'Demo criterion', answer: DEMO_TEXT }],
        status: 'submitted',
        submittedAt: ago(1),
      },
    )
  }

  // ── Handover (S17) ────────────────────────────────────────────────

  await upsert(
    payload,
    'handovers',
    {
      and: [
        { account: { equals: focal } },
        { reason: { equals: 'mandate_end' } },
      ],
    },
    {
      account: focal,
      reason: 'mandate_end',
      scopeLabel: 'Constituency Work roles (demo)',
      items: [
        { label: 'Return shared credentials and documents', done: true, doneAt: ago(1) },
        { label: 'Hand over working-group contact lists', done: false },
        { label: 'Confirm no pending personal-data exports', done: false },
      ],
      dueAt: ahead(14),
      status: 'open',
      openedBy: admin,
      openedAt: ago(3),
    },
  )

  // ── Operational filings (one of each queue) ───────────────────────

  await upsert(
    payload,
    'funding-requests',
    { title: { equals: '[Demo] Funding request' } },
    {
      account: member,
      title: '[Demo] Funding request',
      purpose: DEMO_TEXT,
      amountNumeric: 250,
      currency: 'EUR',
      category: 'project',
      status: 'submitted',
      submittedAt: ago(1),
    },
  )
  await upsert(
    payload,
    'safeguarding-cases',
    {
      and: [
        { reporter: { equals: member } },
        { kind: { equals: 'concern' } },
      ],
    },
    {
      reporter: member,
      kind: 'concern',
      severity: 'low',
      description: DEMO_TEXT,
      status: 'received',
      receivedAt: ago(2),
    },
  )
  await upsert(
    payload,
    'coi-declarations',
    {
      and: [
        { account: { equals: cwFinanceContact } },
        { status: { equals: 'declared' } },
      ],
    },
    {
      account: cwFinanceContact,
      interest: '[Demo] Declared interest',
      details: DEMO_TEXT,
      status: 'declared',
      declaredAt: ago(2),
    },
  )
  await upsert(
    payload,
    'recognition-requests',
    {
      and: [
        { account: { equals: member } },
        { kind: { equals: 'certificate' } },
      ],
    },
    {
      account: member,
      kind: 'certificate',
      purpose: DEMO_TEXT,
      status: 'requested',
      requestedAt: ago(1),
    },
  )
  await upsert(
    payload,
    'partnership-requests',
    { organisationName: { equals: '[Demo] Partner organisation' } },
    {
      account: member,
      organisationName: '[Demo] Partner organisation',
      kind: 'partnership',
      summary: DEMO_TEXT,
      requiresCouncilDecision: false,
      status: 'proposed',
      proposedAt: ago(1),
    },
  )
  await upsert(
    payload,
    'privacy-requests',
    {
      and: [
        { account: { equals: member } },
        { kind: { equals: 'access' } },
      ],
    },
    {
      account: member,
      kind: 'access',
      details: DEMO_TEXT,
      status: 'received',
      dueAt: ahead(30),
      requestedAt: ago(1),
    },
  )

  return {
    decisions: [p1.id, p2.id, p3.id],
    election: election.id,
    selection: selection.id,
  }
}
