/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    accounts: AccountAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    accounts: Account;
    assignments: Assignment;
    'member-profiles': MemberProfile;
    'working-groups': WorkingGroup;
    'wg-progress': WgProgress;
    'content-events': ContentEvent;
    'content-announcements': ContentAnnouncement;
    'content-submissions': ContentSubmission;
    'council-decisions': CouncilDecision;
    'content-coys': ContentCoy;
    'directory-contacts': DirectoryContact;
    'catalogue-resources': CatalogueResource;
    opportunities: Opportunity;
    'feedback-tickets': FeedbackTicket;
    'gys-cycles': GysCycle;
    'gys-contributions': GysContribution;
    'gys-workflow-cycles': GysWorkflowCycle;
    'gys-tracked-contributions': GysTrackedContribution;
    'wg-activities': WgActivity;
    'cp-call-slots': CpCallSlot;
    'content-drafts': ContentDraft;
    'consultation-contributions': ConsultationContribution;
    'password-resets': PasswordReset;
    'ngo-seats': NgoSeat;
    'ngo-requests': NgoRequest;
    'membership-appeals': MembershipAppeal;
    'notification-prefs': NotificationPref;
    'audit-log': AuditLog;
    'push-subscriptions': PushSubscription;
    'notification-outbox': NotificationOutbox;
    'resource-issues': ResourceIssue;
    'resource-reviews': ResourceReview;
    'research-notes': ResearchNote;
    'email-verification-tokens': EmailVerificationToken;
    'decision-proposals': DecisionProposal;
    'decision-flags': DecisionFlag;
    'decision-comments': DecisionComment;
    'decision-ballots': DecisionBallot;
    'decision-vetoes': DecisionVetoe;
    'decision-events': DecisionEvent;
    elections: Election;
    'election-candidates': ElectionCandidate;
    'election-voters': ElectionVoter;
    'election-ballots': ElectionBallot;
    selections: Selection;
    'selection-committee': SelectionCommittee;
    'selection-applications': SelectionApplication;
    'selection-evaluations': SelectionEvaluation;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    assignments: AssignmentsSelect<false> | AssignmentsSelect<true>;
    'member-profiles': MemberProfilesSelect<false> | MemberProfilesSelect<true>;
    'working-groups': WorkingGroupsSelect<false> | WorkingGroupsSelect<true>;
    'wg-progress': WgProgressSelect<false> | WgProgressSelect<true>;
    'content-events': ContentEventsSelect<false> | ContentEventsSelect<true>;
    'content-announcements': ContentAnnouncementsSelect<false> | ContentAnnouncementsSelect<true>;
    'content-submissions': ContentSubmissionsSelect<false> | ContentSubmissionsSelect<true>;
    'council-decisions': CouncilDecisionsSelect<false> | CouncilDecisionsSelect<true>;
    'content-coys': ContentCoysSelect<false> | ContentCoysSelect<true>;
    'directory-contacts': DirectoryContactsSelect<false> | DirectoryContactsSelect<true>;
    'catalogue-resources': CatalogueResourcesSelect<false> | CatalogueResourcesSelect<true>;
    opportunities: OpportunitiesSelect<false> | OpportunitiesSelect<true>;
    'feedback-tickets': FeedbackTicketsSelect<false> | FeedbackTicketsSelect<true>;
    'gys-cycles': GysCyclesSelect<false> | GysCyclesSelect<true>;
    'gys-contributions': GysContributionsSelect<false> | GysContributionsSelect<true>;
    'gys-workflow-cycles': GysWorkflowCyclesSelect<false> | GysWorkflowCyclesSelect<true>;
    'gys-tracked-contributions': GysTrackedContributionsSelect<false> | GysTrackedContributionsSelect<true>;
    'wg-activities': WgActivitiesSelect<false> | WgActivitiesSelect<true>;
    'cp-call-slots': CpCallSlotsSelect<false> | CpCallSlotsSelect<true>;
    'content-drafts': ContentDraftsSelect<false> | ContentDraftsSelect<true>;
    'consultation-contributions': ConsultationContributionsSelect<false> | ConsultationContributionsSelect<true>;
    'password-resets': PasswordResetsSelect<false> | PasswordResetsSelect<true>;
    'ngo-seats': NgoSeatsSelect<false> | NgoSeatsSelect<true>;
    'ngo-requests': NgoRequestsSelect<false> | NgoRequestsSelect<true>;
    'membership-appeals': MembershipAppealsSelect<false> | MembershipAppealsSelect<true>;
    'notification-prefs': NotificationPrefsSelect<false> | NotificationPrefsSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    'push-subscriptions': PushSubscriptionsSelect<false> | PushSubscriptionsSelect<true>;
    'notification-outbox': NotificationOutboxSelect<false> | NotificationOutboxSelect<true>;
    'resource-issues': ResourceIssuesSelect<false> | ResourceIssuesSelect<true>;
    'resource-reviews': ResourceReviewsSelect<false> | ResourceReviewsSelect<true>;
    'research-notes': ResearchNotesSelect<false> | ResearchNotesSelect<true>;
    'email-verification-tokens': EmailVerificationTokensSelect<false> | EmailVerificationTokensSelect<true>;
    'decision-proposals': DecisionProposalsSelect<false> | DecisionProposalsSelect<true>;
    'decision-flags': DecisionFlagsSelect<false> | DecisionFlagsSelect<true>;
    'decision-comments': DecisionCommentsSelect<false> | DecisionCommentsSelect<true>;
    'decision-ballots': DecisionBallotsSelect<false> | DecisionBallotsSelect<true>;
    'decision-vetoes': DecisionVetoesSelect<false> | DecisionVetoesSelect<true>;
    'decision-events': DecisionEventsSelect<false> | DecisionEventsSelect<true>;
    elections: ElectionsSelect<false> | ElectionsSelect<true>;
    'election-candidates': ElectionCandidatesSelect<false> | ElectionCandidatesSelect<true>;
    'election-voters': ElectionVotersSelect<false> | ElectionVotersSelect<true>;
    'election-ballots': ElectionBallotsSelect<false> | ElectionBallotsSelect<true>;
    selections: SelectionsSelect<false> | SelectionsSelect<true>;
    'selection-committee': SelectionCommitteeSelect<false> | SelectionCommitteeSelect<true>;
    'selection-applications': SelectionApplicationsSelect<false> | SelectionApplicationsSelect<true>;
    'selection-evaluations': SelectionEvaluationsSelect<false> | SelectionEvaluationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Account;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface AccountAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  id: number;
  name: string;
  firstName?: string | null;
  lastName?: string | null;
  phone?: string | null;
  gender?: string | null;
  genderOther?: string | null;
  ageBand?: string | null;
  dateOfBirth?: string | null;
  minorityGroups?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  minorityOther?: string | null;
  region?: string | null;
  nationality?: string | null;
  country: string;
  motivation?: string | null;
  entityType: 'individual' | 'organization';
  /**
   * Organisation posting trust override; empty derives trust from a published posting.
   */
  postingTrust?: ('trusted' | 'review_required') | null;
  /**
   * Staff note recorded with the posting-trust override.
   */
  postingTrustNote?: string | null;
  membershipTrack: 'network' | 'constituency_work';
  organizationName?: string | null;
  organizationType?: string | null;
  isUnfcccAdmitted?: boolean | null;
  orgOperateIn?: string | null;
  orgWebsite?: string | null;
  orgSocial?: string | null;
  orgMission?: string | null;
  dcpName?: string | null;
  dcpEmail?: string | null;
  dcpPhone?: string | null;
  ycpName?: string | null;
  ycpEmail?: string | null;
  ycpPhone?: string | null;
  under18?: boolean | null;
  guardianName?: string | null;
  guardianEmail?: string | null;
  guardianConsent?: boolean | null;
  memberOfAccreditedNgo?: boolean | null;
  coiDeclared?: boolean | null;
  coiDetails?: string | null;
  youthAffiliation?: string | null;
  acceptCodeOfConduct?: boolean | null;
  acceptDataProtection?: boolean | null;
  acceptPrinciples?: boolean | null;
  acceptCoiPolicy?: boolean | null;
  policiesAccepted?: boolean | null;
  membershipPolicyVersion?: string | null;
  privacyConsent?: boolean | null;
  privacyConsentAt?: string | null;
  privacyNoticeVersion?: string | null;
  privacyConsentWithdrawnAt?: string | null;
  memberStatus?: ('pending_course' | 'verified' | 'suspended') | null;
  hubAccessStatus?: ('pending_course' | 'active' | 'suspended') | null;
  membershipStatus?:
    | (
        | 'registered'
        | 'course_passed'
        | 'awaiting_onboarding'
        | 'active'
        | 'renewal_due'
        | 'expired'
        | 'terminated'
        | 'rejected'
      )
    | null;
  constituencyWorkStatus?: ('' | 'pending_onboarding' | 'active') | null;
  onboardingCohort?: string | null;
  renewalDueAt?: string | null;
  membershipEndedAt?: string | null;
  membershipEndReason?: string | null;
  role: 'member' | 'admin' | 'focal_point' | 'wg_contact' | 'ngo_admin';
  teamRoles?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  wgInterests?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  appointmentEvidence?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  coursePassedAt?: string | null;
  courseScore?: number | null;
  verifiedAt?: string | null;
  verifiedBy?: string | null;
  emailVerifiedAt?: string | null;
  principalType?: ('human' | 'service') | null;
  mustChangePassword?: boolean | null;
  legacyPasswordHash?: string | null;
  legacyPasswordSalt?: string | null;
  lastLoginAt?: string | null;
  legacyId?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'accounts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assignments".
 */
export interface Assignment {
  id: number;
  account: number | Account;
  scopeType:
    | 'team'
    | 'working_group'
    | 'negotiation_track'
    | 'negotiation_project'
    | 'platform_body'
    | 'body'
    | 'organization'
    | 'platform';
  scopeId: string;
  role: string;
  appointmentEvidence?: string | null;
  status: 'active' | 'inactive' | 'expired';
  startsAt?: string | null;
  endsAt?: string | null;
  assignedBy?: (number | null) | Account;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-profiles".
 */
export interface MemberProfile {
  id: number;
  account: number | Account;
  displayName: string;
  headline?: string | null;
  bio?: string | null;
  pronouns?: string | null;
  expertiseTags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  directoryVisibility?: ('private' | 'members' | 'public') | null;
  showCountry?: boolean | null;
  showOrganization?: boolean | null;
  showWorkingGroups?: boolean | null;
  showRoles?: boolean | null;
  roleTitle?: string | null;
  revision?: number | null;
  hasPhoto?: boolean | null;
  photoUpdatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "working-groups".
 */
export interface WorkingGroup {
  id: number;
  slug: string;
  name: string;
  monogram?: string | null;
  focusLine?: string | null;
  description?: string | null;
  cadenceNote?: string | null;
  topic?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  resources?:
    | {
        label: string;
        description?: string | null;
        url: string;
        visibility?: string | null;
        id?: string | null;
      }[]
    | null;
  taskForces?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  whatsappUrl?: string | null;
  groupUrl?: string | null;
  driveUrl?: string | null;
  publicSpace?: boolean | null;
  isActive?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wg-progress".
 */
export interface WgProgress {
  id: number;
  account: number | Account;
  wgSlug: string;
  presentationOk?: boolean | null;
  rulesOk?: boolean | null;
  unlockedAt?: string | null;
  joinedAt?: string | null;
  status?: ('interested' | 'pending_approval' | 'active' | 'inactive' | 'rejected') | null;
  roleInWg?: ('member' | 'contact' | 'lead') | null;
  onboardedBy?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-events".
 */
export interface ContentEvent {
  id: number;
  slug: string;
  title: string;
  type: string;
  startsAt: string;
  endsAt?: string | null;
  description?: string | null;
  wg?: (number | null) | WorkingGroup;
  /**
   * Join link — members only, never published anonymously
   */
  meetingUrl?: string | null;
  recordingUrl?: string | null;
  state: 'published' | 'unpublished';
  legacySource?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-announcements".
 */
export interface ContentAnnouncement {
  id: number;
  slug: string;
  title: string;
  body: string;
  pinned?: boolean | null;
  ctaUrl?: string | null;
  ctaLabel?: string | null;
  ctaDeadlineAt?: string | null;
  publishedAt?: string | null;
  state: 'published' | 'unpublished';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-submissions".
 */
export interface ContentSubmission {
  id: number;
  slug: string;
  title: string;
  status: 'open' | 'drafting' | 'internal_review' | 'submitted' | 'archived';
  deadlineAt?: string | null;
  wg?: (number | null) | WorkingGroup;
  draftUrl?: string | null;
  finalUrl?: string | null;
  unfcccUrl?: string | null;
  contributeNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "council-decisions".
 */
export interface CouncilDecision {
  id: number;
  slug: string;
  title: string;
  status: 'proposed' | 'open_for_input' | 'objection_window' | 'adopted' | 'rejected' | 'withdrawn';
  summary?: string | null;
  proposer?: string | null;
  proposalUrl?: string | null;
  finalUrl?: string | null;
  respondNote?: string | null;
  outcomeNote?: string | null;
  inputDeadline?: string | null;
  objectionDeadline?: string | null;
  decidedAt?: string | null;
  statusLog?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-coys".
 */
export interface ContentCoy {
  id: number;
  slug: string;
  type: 'coy' | 'lcoy' | 'rcoy' | 'other';
  title: string;
  country?: string | null;
  city?: string | null;
  region?: string | null;
  startsOn?: string | null;
  endsOn?: string | null;
  datesTbc?: boolean | null;
  status?: string | null;
  applicationsCloseAt?: string | null;
  reviewStatus?: ('pending' | 'approved' | 'rejected') | null;
  organizerName?: string | null;
  organizerOrg?: string | null;
  registerUrl?: string | null;
  websiteUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "directory-contacts".
 */
export interface DirectoryContact {
  id: number;
  group: string;
  roleTitle: string;
  description?: string | null;
  publicEmail?: string | null;
  wg?: (number | null) | WorkingGroup;
  /**
   * Members only
   */
  personName?: string | null;
  /**
   * Members only
   */
  channelValue?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalogue-resources".
 */
export interface CatalogueResource {
  id: number;
  slug: string;
  title: string;
  url: string;
  summary?: string | null;
  publisher?: string | null;
  pathway?: string | null;
  type?: string | null;
  topic?: string | null;
  topics?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  region?: string | null;
  language?: string | null;
  source?: string | null;
  verificationStatus?: ('verified' | 'needs_verification' | 'flagged' | 'retired') | null;
  checkedAt?: string | null;
  retiredAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opportunities".
 */
export interface Opportunity {
  id: number;
  slug?: string | null;
  kind: 'event' | 'workshop' | 'hackathon' | 'opportunity' | 'call' | 'training';
  title: string;
  summary?: string | null;
  body?: string | null;
  format?: ('online' | 'in_person' | 'hybrid') | null;
  location?: string | null;
  region?: string | null;
  startsAt?: string | null;
  endsAt?: string | null;
  deadlineAt?: string | null;
  linkUrl?: string | null;
  organizationName?: string | null;
  orgAccount?: (number | null) | Account;
  status: 'draft' | 'pending_review' | 'published' | 'withdrawn' | 'rejected';
  reviewNote?: string | null;
  reviewedAt?: string | null;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback-tickets".
 */
export interface FeedbackTicket {
  id: number;
  title: string;
  kind: 'bug' | 'ui_ux' | 'feature' | 'blocker' | 'content' | 'other';
  severity: 'low' | 'normal' | 'high' | 'critical';
  body: string;
  pageUrl?: string | null;
  contextNote?: string | null;
  account?: (number | null) | Account;
  contactEmail?: string | null;
  status: 'new' | 'triaged' | 'in_progress' | 'resolved' | 'declined';
  triageNote?: string | null;
  githubIssueUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gys-cycles".
 */
export interface GysCycle {
  id: number;
  year: number;
  edition?: string | null;
  title: string;
  location?: string | null;
  targetSession?: string | null;
  intro?: string | null;
  note?: string | null;
  fullUrl?: string | null;
  inputsUrl?: string | null;
  inputsDeadlineAt?: string | null;
  releaseUrl?: string | null;
  priorities?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  process?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  archive?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  isCurrent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gys-contributions".
 */
export interface GysContribution {
  id: number;
  cycle: string;
  name: string;
  email: string;
  country?: string | null;
  organization?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gys-workflow-cycles".
 */
export interface GysWorkflowCycle {
  id: number;
  code: string;
  title: string;
  year: number;
  status: 'planning' | 'intake' | 'synthesis' | 'review' | 'consultation' | 'approved' | 'published' | 'archived';
  opensAt?: string | null;
  closesAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gys-tracked-contributions".
 */
export interface GysTrackedContribution {
  id: number;
  cycle: number | GysWorkflowCycle;
  title: string;
  body?: string | null;
  theme?: string | null;
  region?: string | null;
  country?: string | null;
  submitterType?: string | null;
  organization?: string | null;
  source?: string | null;
  externalId?: string | null;
  rawAnswers?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  author?: (number | null) | Account;
  reviewer?: (number | null) | Account;
  status: 'submitted' | 'triaged' | 'drafting' | 'needs_review' | 'approved' | 'rejected' | 'published';
  version?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wg-activities".
 */
export interface WgActivity {
  id: number;
  wgSlug: string;
  kind: string;
  title: string;
  body?: string | null;
  startsAt?: string | null;
  endsAt?: string | null;
  url?: string | null;
  taskForceSlug?: string | null;
  createdBy?: (number | null) | Account;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cp-call-slots".
 */
export interface CpCallSlot {
  id: number;
  hostAccount: number | Account;
  startsAt: string;
  durationMin?: number | null;
  meetingUrl?: string | null;
  status: 'open' | 'booked' | 'cancelled';
  bookedByAccount?: (number | null) | Account;
  bookedAt?: string | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-drafts".
 */
export interface ContentDraft {
  id: number;
  contentType: 'event' | 'announcement' | 'resource' | 'coy' | 'opportunity';
  contentKey: string;
  status: 'draft' | 'in_review' | 'changes_requested' | 'approved' | 'published' | 'rejected';
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  author?: (number | null) | Account;
  reviewer?: (number | null) | Account;
  reviewNote?: string | null;
  submittedAt?: string | null;
  reviewedAt?: string | null;
  publishedAt?: string | null;
  revision?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-contributions".
 */
export interface ConsultationContribution {
  id: number;
  kind: string;
  name?: string | null;
  email?: string | null;
  organization?: string | null;
  body?: string | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  consentGiven?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "password-resets".
 */
export interface PasswordReset {
  id: number;
  account: number | Account;
  email: string;
  tokenHash: string;
  expiresAt: string;
  usedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ngo-seats".
 */
export interface NgoSeat {
  id: number;
  orgAccount: number | Account;
  memberAccount?: (number | null) | Account;
  email?: string | null;
  name?: string | null;
  seatRole: 'owner' | 'representative' | 'viewer' | 'affiliate';
  status: 'invited' | 'requested' | 'active' | 'revoked' | 'declined';
  inviteTokenHash?: string | null;
  inviteExpiresAt?: string | null;
  invitedBy?: (number | null) | Account;
  acceptedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ngo-requests".
 */
export interface NgoRequest {
  id: number;
  orgAccount: number | Account;
  kind: 'submit' | 'endorse' | 'represent' | 'deadline' | 'other' | 'badge_support';
  title: string;
  body?: string | null;
  deadlineAt?: string | null;
  status?: ('open' | 'in_progress' | 'done' | 'declined') | null;
  createdBy?: (number | null) | Account;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-appeals".
 */
export interface MembershipAppeal {
  id: number;
  account: number | Account;
  statement: string;
  identityKind?: string | null;
  proofContentType?: string | null;
  proofByteSize?: number | null;
  status?: ('submitted' | 'granted' | 'upheld') | null;
  reviewNote?: string | null;
  reviewedBy?: (number | null) | Account;
  reviewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-prefs".
 */
export interface NotificationPref {
  id: number;
  account: number | Account;
  timezone?: string | null;
  digestDay?: number | null;
  digestHourUtc?: number | null;
  email?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  pushEnabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  actor?: (number | null) | Account;
  actorEmail?: string | null;
  action: string;
  targetType?: string | null;
  targetId?: string | null;
  reason?: string | null;
  before?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  after?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  requestId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-subscriptions".
 */
export interface PushSubscription {
  id: number;
  account: number | Account;
  endpoint: string;
  keys:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  userAgent?: string | null;
  disabledAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-outbox".
 */
export interface NotificationOutbox {
  id: number;
  account: number | Account;
  category: 'digest' | 'deadline' | 'announcement';
  templateKey: string;
  sourceType?: string | null;
  sourceId?: string | null;
  deduplicationKey: string;
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  availableAt: string;
  status: 'queued' | 'sent' | 'failed' | 'suppressed';
  attempts?: number | null;
  leaseUntil?: string | null;
  providerMessageId?: string | null;
  lastErrorCode?: string | null;
  sentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resource-issues".
 */
export interface ResourceIssue {
  id: number;
  resourceSlug: string;
  kind: 'broken' | 'outdated' | 'tags' | 'duplicate' | 'other';
  detail: string;
  reportedBy?: (number | null) | Account;
  resolvedAt?: string | null;
  resolvedBy?: (number | null) | Account;
  reviewId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resource-reviews".
 */
export interface ResourceReview {
  id: number;
  resourceSlug: string;
  fingerprint?: string | null;
  status: 'verified' | 'needs_changes' | 'retired';
  note?: string | null;
  checks?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  reviewedBy?: (number | null) | Account;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-notes".
 */
export interface ResearchNote {
  id: number;
  account: number | Account;
  kind?: 'research_note' | null;
  title: string;
  note: string;
  citations:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status?: ('draft' | 'pending_review' | 'approved' | 'applied' | 'rejected') | null;
  idempotencyKey?: string | null;
  approvedBy?: (number | null) | Account;
  appliedBy?: (number | null) | Account;
  appliedAt?: string | null;
  reviewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-verification-tokens".
 */
export interface EmailVerificationToken {
  id: number;
  account: number | Account;
  tokenHash: string;
  expiresAt: string;
  usedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "decision-proposals".
 */
export interface DecisionProposal {
  id: number;
  title: string;
  context: string;
  proposalText: string;
  decisionType: 'standard' | 'snap' | 'og_standard' | 'og_snap' | 'press_release';
  body: 'council' | 'working_group' | 'operational_team' | 'gct' | 'constituency';
  bodyRef?: string | null;
  snapJustification?: string | null;
  snapDeadline?: string | null;
  status:
    | 'draft'
    | 'consultation'
    | 'revision'
    | 'decision'
    | 'voting'
    | 'adopted'
    | 'vetoed'
    | 'withdrawn'
    | 'failed_quorum'
    | 'rejected';
  proposedBy: number | Account;
  contactPersons: (number | Account)[];
  presentedAt?: string | null;
  consultationEndsAt?: string | null;
  revisionEndsAt?: string | null;
  decisionEndsAt?: string | null;
  votingEndsAt?: string | null;
  eligibleVoterCount?: number | null;
  ballotOptions?:
    | {
        option: string;
        id?: string | null;
      }[]
    | null;
  adoptedVia?: ('consensus' | 'consensus_with_reservations' | 'vote' | 'meeting') | null;
  decidedAt?: string | null;
  resultSummary?: string | null;
  trackerUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "decision-flags".
 */
export interface DecisionFlag {
  id: number;
  proposal: number | DecisionProposal;
  kind: 'red' | 'grey';
  rationaleCategory?:
    | (
        | 'principles_violation'
        | 'coc_violation'
        | 'science_contradiction'
        | 'past_decision_contradiction'
        | 'process_noncompliance'
        | 'mission_misalignment'
        | 'inadequate_consultation'
        | 'grey_flag_unsatisfactory'
      )
    | null;
  reason: string;
  alternative?: string | null;
  raisedBy: number | Account;
  status: 'open' | 'addressed' | 'withdrawn' | 'nullified';
  responseNote?: string | null;
  respondedBy?: (number | null) | Account;
  respondedAt?: string | null;
  raisedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "decision-comments".
 */
export interface DecisionComment {
  id: number;
  proposal: number | DecisionProposal;
  account: number | Account;
  body: string;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "decision-ballots".
 */
export interface DecisionBallot {
  id: number;
  proposal: number | DecisionProposal;
  account: number | Account;
  choice: string;
  castAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "decision-vetoes".
 */
export interface DecisionVetoe {
  id: number;
  proposal: number | DecisionProposal;
  requesterKind: 'org' | 'org_global_south' | 'wg_or_ot';
  groupKey: string;
  reasoning: string;
  requestedBy: number | Account;
  status: 'pending' | 'confirmed' | 'rejected';
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "decision-events".
 */
export interface DecisionEvent {
  id: number;
  proposal: number | DecisionProposal;
  type: string;
  actor?: (number | null) | Account;
  detail?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "elections".
 */
export interface Election {
  id: number;
  title: string;
  kind: 'focal_point' | 'other';
  status: 'announced' | 'nominations' | 'voting' | 'tallying' | 'completed' | 'restart_required' | 'cancelled';
  description?: string | null;
  races: {
    slug: string;
    label: string;
    id?: string | null;
  }[];
  nominationsOpenAt?: string | null;
  nominationsCloseAt?: string | null;
  votingOpensAt?: string | null;
  votingCloseAt?: string | null;
  quorumIndividuals?: number | null;
  quorumOrganisations?: number | null;
  eligibleIndividualCount?: number | null;
  eligibleOrgCount?: number | null;
  result?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  externalRef?: string | null;
  facilitationNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "election-candidates".
 */
export interface ElectionCandidate {
  id: number;
  election: number | Election;
  race: string;
  account: number | Account;
  statement: string;
  videoUrl?: string | null;
  status: 'pending' | 'screened_in' | 'screened_out' | 'withdrawn';
  screeningNote?: string | null;
  nominatedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "election-voters".
 */
export interface ElectionVoter {
  id: number;
  election: number | Election;
  account: number | Account;
  kind: 'individual' | 'organisation';
  tokenHash: string;
  issuedAt: string;
  votedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "election-ballots".
 */
export interface ElectionBallot {
  id: number;
  election: number | Election;
  race: string;
  voterTokenHash: string;
  kind: 'individual' | 'organisation';
  ranks:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  castAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "selections".
 */
export interface Selection {
  id: number;
  title: string;
  opportunityNote: string;
  kind: 'standard' | 'wg_nomination';
  bodyRef?: string | null;
  status: 'committee_forming' | 'open' | 'closed' | 'evaluating' | 'decided' | 'announced' | 'cancelled';
  method: 'colour' | 'numerical';
  criteria?:
    | {
        name: string;
        weightPct: number;
        id?: string | null;
      }[]
    | null;
  deadlineAt?: string | null;
  spotsAvailable?: number | null;
  balanceNote?: string | null;
  selectionSummary?: string | null;
  createdBy: number | Account;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "selection-committee".
 */
export interface SelectionCommittee {
  id: number;
  selection: number | Selection;
  account: number | Account;
  joinedAt: string;
  recusedApplicantIds?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  coiNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "selection-applications".
 */
export interface SelectionApplication {
  id: number;
  selection: number | Selection;
  account: number | Account;
  answers:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  selfFinance?: boolean | null;
  gender?: string | null;
  region?: string | null;
  status: 'submitted' | 'selected' | 'not_selected' | 'withdrawn';
  submittedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "selection-evaluations".
 */
export interface SelectionEvaluation {
  id: number;
  selection: number | Selection;
  application: number | SelectionApplication;
  evaluator: number | Account;
  grade?: ('black' | 'red' | 'orange' | 'yellow' | 'green') | null;
  scores?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  comment?: string | null;
  evaluatedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'accounts';
        value: number | Account;
      } | null)
    | ({
        relationTo: 'assignments';
        value: number | Assignment;
      } | null)
    | ({
        relationTo: 'member-profiles';
        value: number | MemberProfile;
      } | null)
    | ({
        relationTo: 'working-groups';
        value: number | WorkingGroup;
      } | null)
    | ({
        relationTo: 'wg-progress';
        value: number | WgProgress;
      } | null)
    | ({
        relationTo: 'content-events';
        value: number | ContentEvent;
      } | null)
    | ({
        relationTo: 'content-announcements';
        value: number | ContentAnnouncement;
      } | null)
    | ({
        relationTo: 'content-submissions';
        value: number | ContentSubmission;
      } | null)
    | ({
        relationTo: 'council-decisions';
        value: number | CouncilDecision;
      } | null)
    | ({
        relationTo: 'content-coys';
        value: number | ContentCoy;
      } | null)
    | ({
        relationTo: 'directory-contacts';
        value: number | DirectoryContact;
      } | null)
    | ({
        relationTo: 'catalogue-resources';
        value: number | CatalogueResource;
      } | null)
    | ({
        relationTo: 'opportunities';
        value: number | Opportunity;
      } | null)
    | ({
        relationTo: 'feedback-tickets';
        value: number | FeedbackTicket;
      } | null)
    | ({
        relationTo: 'gys-cycles';
        value: number | GysCycle;
      } | null)
    | ({
        relationTo: 'gys-contributions';
        value: number | GysContribution;
      } | null)
    | ({
        relationTo: 'gys-workflow-cycles';
        value: number | GysWorkflowCycle;
      } | null)
    | ({
        relationTo: 'gys-tracked-contributions';
        value: number | GysTrackedContribution;
      } | null)
    | ({
        relationTo: 'wg-activities';
        value: number | WgActivity;
      } | null)
    | ({
        relationTo: 'cp-call-slots';
        value: number | CpCallSlot;
      } | null)
    | ({
        relationTo: 'content-drafts';
        value: number | ContentDraft;
      } | null)
    | ({
        relationTo: 'consultation-contributions';
        value: number | ConsultationContribution;
      } | null)
    | ({
        relationTo: 'password-resets';
        value: number | PasswordReset;
      } | null)
    | ({
        relationTo: 'ngo-seats';
        value: number | NgoSeat;
      } | null)
    | ({
        relationTo: 'ngo-requests';
        value: number | NgoRequest;
      } | null)
    | ({
        relationTo: 'membership-appeals';
        value: number | MembershipAppeal;
      } | null)
    | ({
        relationTo: 'notification-prefs';
        value: number | NotificationPref;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'push-subscriptions';
        value: number | PushSubscription;
      } | null)
    | ({
        relationTo: 'notification-outbox';
        value: number | NotificationOutbox;
      } | null)
    | ({
        relationTo: 'resource-issues';
        value: number | ResourceIssue;
      } | null)
    | ({
        relationTo: 'resource-reviews';
        value: number | ResourceReview;
      } | null)
    | ({
        relationTo: 'research-notes';
        value: number | ResearchNote;
      } | null)
    | ({
        relationTo: 'email-verification-tokens';
        value: number | EmailVerificationToken;
      } | null)
    | ({
        relationTo: 'decision-proposals';
        value: number | DecisionProposal;
      } | null)
    | ({
        relationTo: 'decision-flags';
        value: number | DecisionFlag;
      } | null)
    | ({
        relationTo: 'decision-comments';
        value: number | DecisionComment;
      } | null)
    | ({
        relationTo: 'decision-ballots';
        value: number | DecisionBallot;
      } | null)
    | ({
        relationTo: 'decision-vetoes';
        value: number | DecisionVetoe;
      } | null)
    | ({
        relationTo: 'decision-events';
        value: number | DecisionEvent;
      } | null)
    | ({
        relationTo: 'elections';
        value: number | Election;
      } | null)
    | ({
        relationTo: 'election-candidates';
        value: number | ElectionCandidate;
      } | null)
    | ({
        relationTo: 'election-voters';
        value: number | ElectionVoter;
      } | null)
    | ({
        relationTo: 'election-ballots';
        value: number | ElectionBallot;
      } | null)
    | ({
        relationTo: 'selections';
        value: number | Selection;
      } | null)
    | ({
        relationTo: 'selection-committee';
        value: number | SelectionCommittee;
      } | null)
    | ({
        relationTo: 'selection-applications';
        value: number | SelectionApplication;
      } | null)
    | ({
        relationTo: 'selection-evaluations';
        value: number | SelectionEvaluation;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'accounts';
        value: number | Account;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'accounts';
        value: number | Account;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  name?: T;
  firstName?: T;
  lastName?: T;
  phone?: T;
  gender?: T;
  genderOther?: T;
  ageBand?: T;
  dateOfBirth?: T;
  minorityGroups?: T;
  minorityOther?: T;
  region?: T;
  nationality?: T;
  country?: T;
  motivation?: T;
  entityType?: T;
  postingTrust?: T;
  postingTrustNote?: T;
  membershipTrack?: T;
  organizationName?: T;
  organizationType?: T;
  isUnfcccAdmitted?: T;
  orgOperateIn?: T;
  orgWebsite?: T;
  orgSocial?: T;
  orgMission?: T;
  dcpName?: T;
  dcpEmail?: T;
  dcpPhone?: T;
  ycpName?: T;
  ycpEmail?: T;
  ycpPhone?: T;
  under18?: T;
  guardianName?: T;
  guardianEmail?: T;
  guardianConsent?: T;
  memberOfAccreditedNgo?: T;
  coiDeclared?: T;
  coiDetails?: T;
  youthAffiliation?: T;
  acceptCodeOfConduct?: T;
  acceptDataProtection?: T;
  acceptPrinciples?: T;
  acceptCoiPolicy?: T;
  policiesAccepted?: T;
  membershipPolicyVersion?: T;
  privacyConsent?: T;
  privacyConsentAt?: T;
  privacyNoticeVersion?: T;
  privacyConsentWithdrawnAt?: T;
  memberStatus?: T;
  hubAccessStatus?: T;
  membershipStatus?: T;
  constituencyWorkStatus?: T;
  onboardingCohort?: T;
  renewalDueAt?: T;
  membershipEndedAt?: T;
  membershipEndReason?: T;
  role?: T;
  teamRoles?: T;
  wgInterests?: T;
  appointmentEvidence?: T;
  coursePassedAt?: T;
  courseScore?: T;
  verifiedAt?: T;
  verifiedBy?: T;
  emailVerifiedAt?: T;
  principalType?: T;
  mustChangePassword?: T;
  legacyPasswordHash?: T;
  legacyPasswordSalt?: T;
  lastLoginAt?: T;
  legacyId?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assignments_select".
 */
export interface AssignmentsSelect<T extends boolean = true> {
  account?: T;
  scopeType?: T;
  scopeId?: T;
  role?: T;
  appointmentEvidence?: T;
  status?: T;
  startsAt?: T;
  endsAt?: T;
  assignedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-profiles_select".
 */
export interface MemberProfilesSelect<T extends boolean = true> {
  account?: T;
  displayName?: T;
  headline?: T;
  bio?: T;
  pronouns?: T;
  expertiseTags?: T;
  directoryVisibility?: T;
  showCountry?: T;
  showOrganization?: T;
  showWorkingGroups?: T;
  showRoles?: T;
  roleTitle?: T;
  revision?: T;
  hasPhoto?: T;
  photoUpdatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "working-groups_select".
 */
export interface WorkingGroupsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  monogram?: T;
  focusLine?: T;
  description?: T;
  cadenceNote?: T;
  topic?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  resources?:
    | T
    | {
        label?: T;
        description?: T;
        url?: T;
        visibility?: T;
        id?: T;
      };
  taskForces?: T;
  whatsappUrl?: T;
  groupUrl?: T;
  driveUrl?: T;
  publicSpace?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wg-progress_select".
 */
export interface WgProgressSelect<T extends boolean = true> {
  account?: T;
  wgSlug?: T;
  presentationOk?: T;
  rulesOk?: T;
  unlockedAt?: T;
  joinedAt?: T;
  status?: T;
  roleInWg?: T;
  onboardedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-events_select".
 */
export interface ContentEventsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  type?: T;
  startsAt?: T;
  endsAt?: T;
  description?: T;
  wg?: T;
  meetingUrl?: T;
  recordingUrl?: T;
  state?: T;
  legacySource?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-announcements_select".
 */
export interface ContentAnnouncementsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  body?: T;
  pinned?: T;
  ctaUrl?: T;
  ctaLabel?: T;
  ctaDeadlineAt?: T;
  publishedAt?: T;
  state?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-submissions_select".
 */
export interface ContentSubmissionsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  status?: T;
  deadlineAt?: T;
  wg?: T;
  draftUrl?: T;
  finalUrl?: T;
  unfcccUrl?: T;
  contributeNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "council-decisions_select".
 */
export interface CouncilDecisionsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  status?: T;
  summary?: T;
  proposer?: T;
  proposalUrl?: T;
  finalUrl?: T;
  respondNote?: T;
  outcomeNote?: T;
  inputDeadline?: T;
  objectionDeadline?: T;
  decidedAt?: T;
  statusLog?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-coys_select".
 */
export interface ContentCoysSelect<T extends boolean = true> {
  slug?: T;
  type?: T;
  title?: T;
  country?: T;
  city?: T;
  region?: T;
  startsOn?: T;
  endsOn?: T;
  datesTbc?: T;
  status?: T;
  applicationsCloseAt?: T;
  reviewStatus?: T;
  organizerName?: T;
  organizerOrg?: T;
  registerUrl?: T;
  websiteUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "directory-contacts_select".
 */
export interface DirectoryContactsSelect<T extends boolean = true> {
  group?: T;
  roleTitle?: T;
  description?: T;
  publicEmail?: T;
  wg?: T;
  personName?: T;
  channelValue?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalogue-resources_select".
 */
export interface CatalogueResourcesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  url?: T;
  summary?: T;
  publisher?: T;
  pathway?: T;
  type?: T;
  topic?: T;
  topics?: T;
  region?: T;
  language?: T;
  source?: T;
  verificationStatus?: T;
  checkedAt?: T;
  retiredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opportunities_select".
 */
export interface OpportunitiesSelect<T extends boolean = true> {
  slug?: T;
  kind?: T;
  title?: T;
  summary?: T;
  body?: T;
  format?: T;
  location?: T;
  region?: T;
  startsAt?: T;
  endsAt?: T;
  deadlineAt?: T;
  linkUrl?: T;
  organizationName?: T;
  orgAccount?: T;
  status?: T;
  reviewNote?: T;
  reviewedAt?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback-tickets_select".
 */
export interface FeedbackTicketsSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  severity?: T;
  body?: T;
  pageUrl?: T;
  contextNote?: T;
  account?: T;
  contactEmail?: T;
  status?: T;
  triageNote?: T;
  githubIssueUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gys-cycles_select".
 */
export interface GysCyclesSelect<T extends boolean = true> {
  year?: T;
  edition?: T;
  title?: T;
  location?: T;
  targetSession?: T;
  intro?: T;
  note?: T;
  fullUrl?: T;
  inputsUrl?: T;
  inputsDeadlineAt?: T;
  releaseUrl?: T;
  priorities?: T;
  process?: T;
  archive?: T;
  isCurrent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gys-contributions_select".
 */
export interface GysContributionsSelect<T extends boolean = true> {
  cycle?: T;
  name?: T;
  email?: T;
  country?: T;
  organization?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gys-workflow-cycles_select".
 */
export interface GysWorkflowCyclesSelect<T extends boolean = true> {
  code?: T;
  title?: T;
  year?: T;
  status?: T;
  opensAt?: T;
  closesAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gys-tracked-contributions_select".
 */
export interface GysTrackedContributionsSelect<T extends boolean = true> {
  cycle?: T;
  title?: T;
  body?: T;
  theme?: T;
  region?: T;
  country?: T;
  submitterType?: T;
  organization?: T;
  source?: T;
  externalId?: T;
  rawAnswers?: T;
  author?: T;
  reviewer?: T;
  status?: T;
  version?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wg-activities_select".
 */
export interface WgActivitiesSelect<T extends boolean = true> {
  wgSlug?: T;
  kind?: T;
  title?: T;
  body?: T;
  startsAt?: T;
  endsAt?: T;
  url?: T;
  taskForceSlug?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cp-call-slots_select".
 */
export interface CpCallSlotsSelect<T extends boolean = true> {
  hostAccount?: T;
  startsAt?: T;
  durationMin?: T;
  meetingUrl?: T;
  status?: T;
  bookedByAccount?: T;
  bookedAt?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-drafts_select".
 */
export interface ContentDraftsSelect<T extends boolean = true> {
  contentType?: T;
  contentKey?: T;
  status?: T;
  payload?: T;
  author?: T;
  reviewer?: T;
  reviewNote?: T;
  submittedAt?: T;
  reviewedAt?: T;
  publishedAt?: T;
  revision?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-contributions_select".
 */
export interface ConsultationContributionsSelect<T extends boolean = true> {
  kind?: T;
  name?: T;
  email?: T;
  organization?: T;
  body?: T;
  meta?: T;
  consentGiven?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "password-resets_select".
 */
export interface PasswordResetsSelect<T extends boolean = true> {
  account?: T;
  email?: T;
  tokenHash?: T;
  expiresAt?: T;
  usedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ngo-seats_select".
 */
export interface NgoSeatsSelect<T extends boolean = true> {
  orgAccount?: T;
  memberAccount?: T;
  email?: T;
  name?: T;
  seatRole?: T;
  status?: T;
  inviteTokenHash?: T;
  inviteExpiresAt?: T;
  invitedBy?: T;
  acceptedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ngo-requests_select".
 */
export interface NgoRequestsSelect<T extends boolean = true> {
  orgAccount?: T;
  kind?: T;
  title?: T;
  body?: T;
  deadlineAt?: T;
  status?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-appeals_select".
 */
export interface MembershipAppealsSelect<T extends boolean = true> {
  account?: T;
  statement?: T;
  identityKind?: T;
  proofContentType?: T;
  proofByteSize?: T;
  status?: T;
  reviewNote?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-prefs_select".
 */
export interface NotificationPrefsSelect<T extends boolean = true> {
  account?: T;
  timezone?: T;
  digestDay?: T;
  digestHourUtc?: T;
  email?: T;
  pushEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  actor?: T;
  actorEmail?: T;
  action?: T;
  targetType?: T;
  targetId?: T;
  reason?: T;
  before?: T;
  after?: T;
  requestId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-subscriptions_select".
 */
export interface PushSubscriptionsSelect<T extends boolean = true> {
  account?: T;
  endpoint?: T;
  keys?: T;
  userAgent?: T;
  disabledAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-outbox_select".
 */
export interface NotificationOutboxSelect<T extends boolean = true> {
  account?: T;
  category?: T;
  templateKey?: T;
  sourceType?: T;
  sourceId?: T;
  deduplicationKey?: T;
  payload?: T;
  availableAt?: T;
  status?: T;
  attempts?: T;
  leaseUntil?: T;
  providerMessageId?: T;
  lastErrorCode?: T;
  sentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resource-issues_select".
 */
export interface ResourceIssuesSelect<T extends boolean = true> {
  resourceSlug?: T;
  kind?: T;
  detail?: T;
  reportedBy?: T;
  resolvedAt?: T;
  resolvedBy?: T;
  reviewId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resource-reviews_select".
 */
export interface ResourceReviewsSelect<T extends boolean = true> {
  resourceSlug?: T;
  fingerprint?: T;
  status?: T;
  note?: T;
  checks?: T;
  reviewedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-notes_select".
 */
export interface ResearchNotesSelect<T extends boolean = true> {
  account?: T;
  kind?: T;
  title?: T;
  note?: T;
  citations?: T;
  status?: T;
  idempotencyKey?: T;
  approvedBy?: T;
  appliedBy?: T;
  appliedAt?: T;
  reviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-verification-tokens_select".
 */
export interface EmailVerificationTokensSelect<T extends boolean = true> {
  account?: T;
  tokenHash?: T;
  expiresAt?: T;
  usedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "decision-proposals_select".
 */
export interface DecisionProposalsSelect<T extends boolean = true> {
  title?: T;
  context?: T;
  proposalText?: T;
  decisionType?: T;
  body?: T;
  bodyRef?: T;
  snapJustification?: T;
  snapDeadline?: T;
  status?: T;
  proposedBy?: T;
  contactPersons?: T;
  presentedAt?: T;
  consultationEndsAt?: T;
  revisionEndsAt?: T;
  decisionEndsAt?: T;
  votingEndsAt?: T;
  eligibleVoterCount?: T;
  ballotOptions?:
    | T
    | {
        option?: T;
        id?: T;
      };
  adoptedVia?: T;
  decidedAt?: T;
  resultSummary?: T;
  trackerUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "decision-flags_select".
 */
export interface DecisionFlagsSelect<T extends boolean = true> {
  proposal?: T;
  kind?: T;
  rationaleCategory?: T;
  reason?: T;
  alternative?: T;
  raisedBy?: T;
  status?: T;
  responseNote?: T;
  respondedBy?: T;
  respondedAt?: T;
  raisedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "decision-comments_select".
 */
export interface DecisionCommentsSelect<T extends boolean = true> {
  proposal?: T;
  account?: T;
  body?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "decision-ballots_select".
 */
export interface DecisionBallotsSelect<T extends boolean = true> {
  proposal?: T;
  account?: T;
  choice?: T;
  castAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "decision-vetoes_select".
 */
export interface DecisionVetoesSelect<T extends boolean = true> {
  proposal?: T;
  requesterKind?: T;
  groupKey?: T;
  reasoning?: T;
  requestedBy?: T;
  status?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "decision-events_select".
 */
export interface DecisionEventsSelect<T extends boolean = true> {
  proposal?: T;
  type?: T;
  actor?: T;
  detail?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "elections_select".
 */
export interface ElectionsSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  status?: T;
  description?: T;
  races?:
    | T
    | {
        slug?: T;
        label?: T;
        id?: T;
      };
  nominationsOpenAt?: T;
  nominationsCloseAt?: T;
  votingOpensAt?: T;
  votingCloseAt?: T;
  quorumIndividuals?: T;
  quorumOrganisations?: T;
  eligibleIndividualCount?: T;
  eligibleOrgCount?: T;
  result?: T;
  externalRef?: T;
  facilitationNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "election-candidates_select".
 */
export interface ElectionCandidatesSelect<T extends boolean = true> {
  election?: T;
  race?: T;
  account?: T;
  statement?: T;
  videoUrl?: T;
  status?: T;
  screeningNote?: T;
  nominatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "election-voters_select".
 */
export interface ElectionVotersSelect<T extends boolean = true> {
  election?: T;
  account?: T;
  kind?: T;
  tokenHash?: T;
  issuedAt?: T;
  votedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "election-ballots_select".
 */
export interface ElectionBallotsSelect<T extends boolean = true> {
  election?: T;
  race?: T;
  voterTokenHash?: T;
  kind?: T;
  ranks?: T;
  castAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "selections_select".
 */
export interface SelectionsSelect<T extends boolean = true> {
  title?: T;
  opportunityNote?: T;
  kind?: T;
  bodyRef?: T;
  status?: T;
  method?: T;
  criteria?:
    | T
    | {
        name?: T;
        weightPct?: T;
        id?: T;
      };
  deadlineAt?: T;
  spotsAvailable?: T;
  balanceNote?: T;
  selectionSummary?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "selection-committee_select".
 */
export interface SelectionCommitteeSelect<T extends boolean = true> {
  selection?: T;
  account?: T;
  joinedAt?: T;
  recusedApplicantIds?: T;
  coiNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "selection-applications_select".
 */
export interface SelectionApplicationsSelect<T extends boolean = true> {
  selection?: T;
  account?: T;
  answers?: T;
  selfFinance?: T;
  gender?: T;
  region?: T;
  status?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "selection-evaluations_select".
 */
export interface SelectionEvaluationsSelect<T extends boolean = true> {
  selection?: T;
  application?: T;
  evaluator?: T;
  grade?: T;
  scores?: T;
  comment?: T;
  evaluatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}